project_id = "bplfricyljoythzwulbt"

[functions.send-otp]
verify_jwt = false

[functions.verify-otp]
verify_jwt = false

[functions.reset-password]
verify_jwt = false

[functions.send-notification-email]
verify_jwt = false

[functions.razorpay-payment]
verify_jwt = false

[functions.cashfree-payment]
verify_jwt = false
